name: On PR Approved to Main

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Specify the Java version you need
          distribution: 'oracle'

      - name: Install Maven
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Maven will use this JDK
          distribution: 'oracle'
          cache: 'maven' # Caches Maven dependencies

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
            chrome-version: 127
            install-chromedriver: true

      - name: Install Firefox
        uses: browser-actions/setup-firefox@v1

      - name: Install GeckoDriver
        uses: browser-actions/setup-geckodriver@latest

      - name: Install Edge
        uses: browser-actions/setup-edge@v1

      - name: Build and Run Tests
        run: mvn clean test # This command will compile the code and run the TestNG tests

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/*

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports # Maven Surefire Plugin generates test reports in this directory
